### ISSUE TITLE
Blank first page when converting to any format

### ISSUE THREAD

**Issue by gtache** [jodconverter/jodconverter#252]
Hello,
Thank you for this great library!

I've just got a problem with a file, the first page is blank when converting to pdf, docx, (x)html or txt. 
However, converting using the LO command-line (`convert-to pdf`) or GUI (`Export as...`) gives the correct result.
It happens with LO 6.1.6.3 on Linux (I can try with newer versions if you want).

Here is the file :
[9c_0182_2019_2019_09_12_t.zip](https://github.com/sbraconnier/jodconverter/files/6088711/9c_0182_2019_2019_09_12_t.zip)
It's actually an odt, but I renamed it to .zip because GitHub doesn't allow uploading odts...

Thanks for your time!

**Comment by sbraconnier** [comment]
@gtache Just so you know, I'm working on your issue (for quite some time now), but didn't find any solution yet. I don't undestand why the difference between the command line and using a filter. I've checked out the whole libre office source code to investigate further.... I hope I'll find something... It's a shame that the UNO Api is so badly documented (like the jodconverter project ;)...oops!!).

**Comment by gtache** [comment]
Thanks for the reply! Glad to know I'm not the only one having this problem (but less glad that it seems to be a really complex one)     
Yeah the furthest I've gone with the Uno library is retrieving all the text from the document to check that everything was at least present (and that was with helper methods found online), but like you said, documentation is very lacking...      
I'd say what's missing in the jodconverter doc is the LibreOffice filters and their values (but that's more LibreOffice's job to document them, jodconverter is simply passing the values) and maybe some documentation on how to run a conversion task on a non-installed office manager (without calling the static `JodConverter.convert` method).     
Anyway, I'll hope you'll find what the problem is, good luck!

**Comment by sbraconnier** [comment]
@gtache I just wanted to let you know that it seems it was a bug with LibreOffice since I can't reproduce it anymore using LibreOffice 7.4+. I would appreciate if you could confirm that, even if you have probably given up trying to use JodConverter :P

**Comment by sbraconnier** [comment]
Please feel free to reopen if needed
