### ISSUE TITLE
Images are not shown correctly

### ISSUE THREAD

**Issue by loreflepi** [jodconverter/jodconverter#311]
I've been trying to convert some PDF files, which have presentation format, meaning that their wide is larger than their height. So when we see the resulting image the text is overlapped with other text. This is an example 
![image](https://user-images.githubusercontent.com/12673313/198305316-4a3d9569-4e2a-4845-8657-7b350b8570bc.png)
This is the original image from the PDF
![image](https://user-images.githubusercontent.com/12673313/198305581-eea418c1-5e8b-4691-a414-f4e632d8e541.png)

**Comment by sbraconnier** [comment]
Is it possible for you to provide a sample document?

**Comment by sbraconnier** [comment]
I'll close this one as inactive. Feel free to reopen if needed!
