### ISSUE TITLE
Add publish mode to presentation->html conversion in document-formats.json

### ISSUE THREAD

**Issue by surli** [jodconverter/jodconverter#323]
Hi, 

I recently reviewed our internal custom document-formats.json that we provide in XWiki project to perform office conversion, as part of upgrading the jodconverter dependency. My goal was to getting rid of our internal file to use the standard one provided by jodconverter. However I discovered that we have to keep for now our current file because of one custom property that we have, related of the export of presentation in HTML. 
We currently use a filterData filter on `text/html` presentation filter, like this:
```
 "PRESENTATION": {
                "FilterName": "impress_html_Export",
                // Needed to obtain image files
                "FilterData": {
                    "PublishMode": 0
                }
            },
```

This filter has been added a long time ago as part of https://jira.xwiki.org/browse/XWIKI-11611, you can see in the comment that this publish mode is used to also add screenshots of the slides.
I have a very small project to play with that option here if you want to check: https://github.com/surli/testjodconverter 
Note that without this, the conversion just creates a single html file with only text. 

Now to be honest I have no idea if it would make sense for that option to become a standard option there. Maybe there's a way I could just add that filter without needing to replace the whole document-formats.js? Or maybe it does make sense to have it by default? Let me know what you think.

**Comment by sbraconnier** [comment]
I read the details about the issue described in the xwiki jira and I think it would make sense to make sense to force the default behavior in case it's not set properly by LO/OO.

So I will make that the default behavior in jodconverter. It wll be part of the next version, which should be release somewhere this week.

**Comment by surli** [comment]
Thanks a lot!

**Comment by sbraconnier** [comment]
@surli 

Would it be possible to update your repo in order for me to be able to work with your original odp file?? The file named `Test.odp` is already an HTML file here:
`https://github.com/surli/testjodconverter/tree/master/src/main/resources/odp`

**Comment by surli** [comment]
>  The file named Test.odp is already an HTML file here:
https://github.com/surli/testjodconverter/tree/master/src/main/resources/odp 
  
I'm not sure what you mean: https://github.com/surli/testjodconverter/blob/master/src/main/resources/odp/Test.odp is not an html file, is it?

**Comment by sbraconnier** [comment]
Indeed!! Not sure what happened!! I think I may have opened it manually with Writer instead of Impress. Anyway, forget it ! :P

**Comment by sbraconnier** [comment]
I just want to let you know that I changed my mind about the default value. Since JODConverter can be used as a web application (see all the sample projects), it doesn't make sense to have a default option that would produce multiple files as part of a conversion. Only the main file would be returned to the client.

Instead, I've add the ability for you to overwrite only the document formats you want. Thus, instead of having your own `document-formats.json` file with all the document formats, you can have a file (which is optional) named  `custom-document-formats.json`, which will be load, if provided, after the default `document-formats.json` and the formats from the custom json file will replace those from the default json file.

**Comment by surli** [comment]
> I just want to let you know that I changed my mind about the default value. Since JODConverter can be used as a web application (see all the sample projects), it doesn't make sense to have a default option that would produce multiple files as part of a conversion. Only the main file would be returned to the client.

Ok to be honest I wasn't so sure it would fit any usecase of jodconverter either.

> Instead, I've add the ability for you to overwrite only the document formats you want. Thus, instead of having your own document-formats.json file with all the document formats, you can have a file (which is optional) named custom-document-formats.json, which will be load, if provided, after the default document-formats.json and the formats from the custom json file will replace those from the default json file.

That's perfect for us, thanks.
