### ISSUE TITLE
missing fonts on convertion from docx to pdf

### ISSUE THREAD

**Issue by poloche** [jodconverter/jodconverter#324]
Hi All,
I am working with jodconverter and spring boot over docker and most of the things are working fine, but when my Docx document has some fonts which are not installed in my docker instance when converting the Docx document to pdf results in squares instead of letters.
```
Map<String, Object> filterData = new HashMap<>();
            filterData.put("PageRange", p.getInit() + "-" + p.getLimit());
            filterData.put("SelectPdfVersion",1);

            Map<String, Object> customProperties = new HashMap<>();
            customProperties.put("FilterData", filterData);

            LocalConverter
                    .builder()
                    .officeManager(officeManager)
                    .storeProperties(customProperties)
                    .build()
                    .convert(inputFile.toFile())
                    .to(outputPath.toFile())
                    .execute();
``` 
I have tried converting to pdf/a, ISO 19005 setting up the *SelectPdfVersion* but it did not work, any suggestion is welcome.

![pdf from docx with missed fonts](https://user-images.githubusercontent.com/213901/213504543-12a9c6d1-6b5f-465a-bdef-8f606de44952.png)
![document with custom fonts](https://user-images.githubusercontent.com/213901/213504556-5540ba8c-c84b-4573-8b82-27273d2fa27e.png)
here is how the Docx file is converted to pdf, notice the font in the Docx file is not installed in my machine itself but when I convert it from my machine using the GUI the pdf is converted without the issue I have in docker.

**Comment by sbraconnier** [comment]
I'll close this one as inactive, feel free to reopen if needed.
