### ISSUE TITLE
启动加载异常 bean of type 'org.jodconverter.core.DocumentConverter' that could not be found.

### ISSUE THREAD

**Issue by Dog-Elder** [jodconverter/jodconverter#326]
SpringBoot 2.7.4 启动异常 
我尝试了很多方法 从JDK17更换成JDK8 也尝试了更换SpringBoot 2.7.x 的版本 如何解决这个问题呢?
![Snipaste_2023-02-27_23-41-17](https://user-images.githubusercontent.com/56543937/221609579-c60529b6-d4b4-438a-8548-b2b0f520181e.png)

**Comment by usersina** [comment]
Same issue for me https://github.com/jodconverter/jodconverter/issues/350#issuecomment-1810627182
