### ISSUE TITLE
Custom Page Size

### ISSUE THREAD

**Issue by phoekoby** [jodconverter/jodconverter#333]
Can I  set custom size for Every page in pdf?

**Comment by sbraconnier** [comment]
Is it something you can do without JODConverter (using libreoffice only)?

**Comment by phoekoby** [comment]
Sorry, my question wasn't correct. I need to generate pdf, with one sheet on one page, like this:
![image](https://user-images.githubusercontent.com/90448569/236160213-a04e87df-68db-441f-8617-2a1a925c0ddd.png)
Can I do it with JodConverter?

**Comment by phoekoby** [comment]
> Is it something you can do without JODConverter (using libreoffice only)?

I screenshot above, I set “Fit print range(s) on number of pages”, now I need do it in JodConverter

**Comment by sbraconnier** [comment]
I'll try to find out how it can be done with jodconverter and come back to you in a day or 2.

**Comment by sbraconnier** [comment]
Try this (note that I also change the orientation to landscape, which can be removed):

```java
final File inputFile = new File("in.ods");
final File outputFile = new File("out.pdf");

// Create a filter to change to page style of each sheet of the document.
final Filter changePageStyleFilter = (context, document, chain) -> {

    // Use the StyleFamiliesSupplier interface to get the XNameAccess interface of the actual style families.
    final XStyleFamiliesSupplier styleFamiliesSupplier = Lo.qi(XStyleFamiliesSupplier.class, document);
    final XNameAccess styleFamilies = Lo.qi(XNameAccess.class, styleFamiliesSupplier.getStyleFamilies());
    // Access the 'PageStyles' Family
    final XNameContainer pageStyleFamily = Lo.qi(XNameContainer.class, styleFamilies.getByName("PageStyles"));

    // No we must go through all the sheets to change the page style of each sheet.
    final XSpreadsheetDocument spreadsheetDocument = Lo.qi(XSpreadsheetDocument.class, document);
    final XSpreadsheets sheets = spreadsheetDocument.getSheets();
    final XIndexAccess indexedSheets = Lo.qi(XIndexAccess.class, sheets);
    final int count = indexedSheets.getCount();
    for (int i = 0; i < count; i++) {

        // We must change the page style properties of the spreadsheet.

        // First get the properties of the page style for this spreadsheet.
        final XSpreadsheet sheet = Lo.qi(XSpreadsheet.class, indexedSheets.getByIndex(i));
        final XPropertySet sheetProperties = Lo.qi(XPropertySet.class, sheet);
        final String pageStyleName = (String) sheetProperties.getPropertyValue("PageStyle");
        final XStyle pageStyle = Lo.qi(XStyle.class, pageStyleFamily.getByName(pageStyleName));
        final XPropertySet pageStyleProps = Lo.qi(XPropertySet.class, pageStyle);

        // Set the ScaleToPages property to 1, which is the programmatic equivalent
        // for setting the page style scaling mode option (Sheet tab) to:
        // "Fit print rage(s) on number of pages"
        pageStyleProps.setPropertyValue("ScaleToPages", (short) 1);

        // Change the print orientation to "landscape" and the page size, which is
        // the programmatic equivalent for setting the page style orientation (Page tab) to:
        // Landscape
        // REMOVE  TFOLLOWING 3 LINES THIS IF YOU DON'T WANT TO CHANGE THE ORIENTATION TO LANDSCAPE.
        pageStyleProps.setPropertyValue("IsLandscape", true);
        final Size pageSize = (Size) AnyConverter.toObject(Size.class, pageStyleProps.getPropertyValue("Size"));
        pageStyleProps.setPropertyValue("Size", new Size(pageSize.Height, pageSize.Width));
    }
};

LocalConverter
        .builder()
        .officeManager(manager)
        .filterChain(changePageStyleFilter)
        .build()
        .convert(inputFile)
        .to(outputFile)
        .execute();
```

**Comment by phoekoby** [comment]
Thanks! I have another questing, can I export Sheet's Name in names of pages in PDF??

**Comment by sbraconnier** [comment]
Hmm... again, I'm not sure I understand your question ? What is a name of page ?? :)

**Comment by phoekoby** [comment]
I meant bookmarks, I export sheet name to bookmarks:
![image](https://github.com/jodconverter/jodconverter/assets/90448569/a2e7c1d3-cd03-4171-9a82-4d38004b18a0)
But when I convert excel sheet to single page there are no bookmarks in the resulting pdf

**Comment by sbraconnier** [comment]
Oh ok, I understand now... I'll take a look.

**Comment by sbraconnier** [comment]
We have to find a way to do it first without jodconverter... Are you able do reproduce this behavior without jodconverter ??

**Comment by phoekoby** [comment]
I'm trying to find out how to do it, but I think it's a bug in LibreOffice, because I can not export bookmarks and moreover resulting PDF is not correct:
[Example.pdf](https://github.com/jodconverter/jodconverter/files/11456011/Example.pdf)
This file is full blank, but I have this file:
[Example.xlsx](https://github.com/jodconverter/jodconverter/files/11456025/Example.xlsx)

**Comment by sbraconnier** [comment]
Have you tried with the latest libreoffice version ? It works on my end. You example xlsx file is a bit extreme tho! The output is not readable :)

**Comment by phoekoby** [comment]
Can you send me your examples??

**Comment by sbraconnier** [comment]
Which version of libreoffice are you using ?

**Comment by phoekoby** [comment]
> Which version of libreoffice are you using ?

7.5.2.2

**Comment by phoekoby** [comment]
Can I find out the size of the filled area (of the whole table) in an excel file?

**Comment by sbraconnier** [comment]
Hmm I'm not sure what you want to do exactly. When I try to find if something can be done programatically, I often look at [this guide](https://flywire.github.io/lo-p/index.html), maybe you will find an example or something that will put you in the right direction.

**Comment by sbraconnier** [comment]
I'll close this one. Feel free to reopen if needed.
