### ISSUE TITLE
Issues with converting Excel to HTML

### ISSUE THREAD

**Issue by XBai-193** [jodconverter/jodconverter#335]
When converting an xlsx file to HTML, if a cell contains multiple images, only one image is rendered correctly and the rest appear after the </table> tag, causing the original content of the file to not display properly.

**Comment by XBai-193** [comment]
the tag <table>

**Comment by XBai-193** [comment]
the tag \<table\>

**Comment by XBai-193** [comment]
I didn't use any other tools to convert it, but I tested it in non-open source software and it displayed normally. Right now, we're working on implementing a feature to preview Excel on a web page, and that's when I stumbled upon this issue.

**Comment by XBai-193** [comment]
> Have you tried the conversion without jodconverter ?? Is the behavior the same ?
I didn't use any other tools to convert it, but I tested it in non-open source software and it displayed normally. Right now, we're working on implementing a feature to preview Excel on a web page, and that's when I stumbled upon this issue.

**Comment by sbraconnier** [comment]
Could you provide a sample document I could work with to investigate the issue?

**Comment by XBai-193** [comment]
I am using a simple example to test, like this.
[test.xlsx](https://github.com/jodconverter/jodconverter/files/11587618/test.xlsx)


> 您能否提供我可以用于调查该问题的示例文档？

**Comment by sbraconnier** [comment]
Not sure if this question is still relevant, but I'm not able to properly convert this document to HTML without jodconverter. So It's not related to jodconverter. You can reopen the issue if you are able to manually convert the document (using LibreOffice or OpenOffice only using the "save as" option), but ig not, you should report this to the LO/OO team.
