### ISSUE TITLE
Unable to connect to external liberoffice when deploying springboot applications using Docker

### ISSUE THREAD

**Issue by liulisanwan** [jodconverter/jodconverter#339]
I looked at the source code and found that the socket method parameter under org. jdconverter. local. office. OfficeUrl is connected to 127.0.0.1. Is there any other way to avoid this issue

**Comment by liulisanwan** [comment]
use 4.3.0

**Comment by sbraconnier** [comment]
You can now set the hostname youself with a more recent version of jodconverter.
