### ISSUE TITLE
LibreOffice not starting when run from Systemd / tomcat user

### ISSUE THREAD

**Issue by yaguesgeek** [jodconverter/jodconverter#340]
We are using a web application developed in Java with the Spring Boot framework. This application is deployed on a Tomcat application server.

The application provides a REST service for converting .doc files to .pdf format. We are using JODConverter 4.4.2 and OpenOffice 4 for this purpose. We start the OpenOffice processes using LocalOfficeManager.builder().

        
		OfficeManager officeManager = null; 
		officeManager = LocalOfficeManager.builder()
			.install()
			.officeHome(openOfficePath)
			.portNumbers(2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011)
			.taskExecutionTimeout(200000L)
			.taskQueueTimeout(200000L)
			.build();

		try {
			officeManager.start();
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
		return officeManager;					
   

The issue arises when restarting the server and expecting it to automatically provide service upon startup. However, it appears that the 'tomcat' user does not have sufficient permissions. Tomcat log:

Full error log attached
[catalina.log](https://github.com/jodconverter/jodconverter/files/11815992/catalina.log)

I suspect these issues are caused by insufficient permissions for the 'tomcat' user. Could you please advise on how to resolve this? I will closely monitor any feedback and respond promptly

@sbraconnier  I believe you have addressed this in other issues such as:
https://github.com/jodconverter/jodconverter/issues/189
But I have not found a definitive solution due to lack of feedback, I do have the root password.

**Comment by sbraconnier** [comment]
Sorry for the long delay.

Do you still need help with this ? By the way, there is a jodconverter starter for spring boot so you don't have to start it yourself. Take a look [here](https://github.com/jodconverter/jodconverter-samples/tree/main/samples/spring-boot-rest) for an example.

**Comment by sbraconnier** [comment]
Closing this one. Feel free to reopen if needed.
