### ISSUE TITLE
An error is reported after the office manager Temporary folder is deleted

### ISSUE THREAD

**Issue by llans250** [jodconverter/jodconverter#346]
## Hi, Project Contributors

   Today， I get an exception from the online system,the error is as follows, 

![1691070008941](https://github.com/jodconverter/jodconverter/assets/23186632/b1c584bc-eeda-4c8b-9bae-d49a7f7c16c6)

## Cause

I found that the reason for this issue is that the folder corresponding to the tempDir attribute of the OfficeManager class was deleted, and the existence of the tempDir directory was not detected during conversion, resulting in the inability to write temporary files during conversion。When Jodconverter is running on Linux/Centos, in the default configuration, the path corresponding to “tempDir“ is ”/tmp“, as shown in the above figure. However, there is a problem where files or folders in this path can be deleted at any time, and the folder on which Jodconverter is stored in this directory is deleted. Jodconverter will not run, which I believe is a bug and I hope the author can fix this issue in a timely manner.

## Project Running Enviroment
 
   Ceontos7
   LibOffice7.4.4
   JDK8
   Jodconverter4.4.6

**Comment by sbraconnier** [comment]
Hello

You can set the [workingDir](https://github.com/jodconverter/jodconverter/wiki/Configuration#file_folderworkingdir) property to avoid this problem. We cannot really choose any other random directory so you'll have to set it manually I'm afraid.

**Comment by llans250** [comment]
thanks guys
