### ISSUE TITLE
Converting spreadsheetML (XML Spreadsheet 2003) to XLSX (Excel Workbook) results in timeout

### ISSUE THREAD

**Issue by niemand23real** [jodconverter/jodconverter#347]
Hi there,

A couple of days ago I got an urgent request to automate conversion from XML Spreadsheet 2003 to Excel Workbook. Naturally, I thought that there would be a lot of libraries for this, but I was surprised that to find out that the solutions are quite limited. After a lot of googling (and playing with the soffice command and with some python libraries) I stumbled upon this project and also found [this](https://github.com/jodconverter/jodconverter/issues/145) thread.

So I used the code from there and I played a little with the taskExecutionTimeout:

`LocalOfficeManager officeManager = LocalOfficeManager
			        .builder()
			        .install()
			        .taskExecutionTimeout(tenMinutesInMillis)
			        .maxTasksPerProcess(50)
			        .build();`

The problem is that I keep getting a task conversion timeout:

`Unable to convert file. Reason: Task did not complete within timeout (600000 ms): LocalConversionTask{source=SourceDocumentSpecsFromFile{file=ReportL.XLS.xml, format=null}, loadProperties={ReadOnly=true, Hidden=true, UpdateDocMode=0}, target=TargetDocumentSpecsFromFile{file=output.xlsx, format=xlsx}, storeProperties=null, useStreamAdapters=false}`

The source file has 1.8 mb and is a little complex meaning that it has formulas and custom styles. 

Can you please tell me if I need to increase the timeout any more? Is it 100 percent clear that this is the only thing that needs to be checked? 

The machine where the code runs is Linux RedHat 8.8 and the version for LibreOffice is:
`LibreOffice 6.4.7.2 40(Build:2)
`

Unfortunately, I cannot provide the source file as it contains some sensitive data but all I can say is that it's in XML Spreadsheet 2003 format :

`<?xml version="1.0" encoding="utf-16"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"><DocumentProperties xmlns="urn:schemas-microsoft-com:office:office"><LastAuthor>....`

**Comment by niemand23real** [comment]
Update:
Checking the logs I saw this:
`Exception in thread "jodconverter-offprocmng-0" java.lang.NoClassDefFoundError: com/sun/star/comp/loader/JavaLoader`
So I added jurt-4.1.2.jar to the classpath and now I am getting:
`Unable to convert file. Reason: Local conversion failed`
Any idea what I can do next?

**Comment by niemand23real** [comment]
Update: I changed extension for the source file from xml to xls -> ReportL.XLS.. This time it worked, but the resulting file is completely messed out, meaning that styling is lost and there are lots of columns where I see:
`00</Data></Cell><Cell ss:StyleID="item_normal"><Data ss:Type="String">0`
Is XML Spreadsheet 2003 really supported?

**Comment by sbraconnier** [comment]
Sorry for the delay. Do you still need help with this ?

Are you able to properly convert your document using libreoffice without JODConverter ?

**Comment by niemand23real** [comment]
Hi, no it seems that conversion is not working properly using LIbreOffice as well. In the meantime, I found another Java library (Aspose Cells) and I was able to convert using their library but this did not meet the business requirements since it's a paid library so my organization decided to use a RPA approach instead.

**Comment by sbraconnier** [comment]
Ok. Thanks for your feedback! You may try to contact the LibreOffice team with your problem so they can support this in the future. Good luck.
