### ISSUE TITLE
Cannot find a valid unoloader.jar path.

### ISSUE THREAD

**Issue by kyusang1542** [jodconverter/jodconverter#348]
I have installed version 7.6 of LibreOffice.
The path is the default path and was installed in C:\Program Files\LibreOffice.

The dependency you added looks like this

```
<dependency>
        <groupId>org.jodconverter</groupId>
        <artifactId>jodconverter-local-lo</artifactId>
        <version>4.4.6</version>
</dependency>
 <dependency>
        <groupId>org.libreoffice</groupId>
        <artifactId>unoloader</artifactId>
        <version>7.4.1</version>
</dependency>
```

But when it actually works, it doesn't find the path.

```
java.io.FileNotFoundException: C:\Users\***\.m2\repository\org\libreoffice\libreoffice\7.4.1\unoloader.jar
```

The path to the actual unoloader.jar file is shown below.

```
C:\Users\***\.m2\repository\org\libreoffice\unoloader\7.4.1\unoloader.jar
```

If you copy the unoloader.jar and put it in the path that is causing the problem, it works fine.

How should I resolve this?
Can I use a different version as an alternative?

**Comment by sbraconnier** [comment]
I'm not sure I understand the problem. I'm not familiar with the unoloader. Why do you need this jar for?

**Comment by sbraconnier** [comment]
Closing this on. Feel free to reopen if needed.
