### ISSUE TITLE
While Excel to pdf convertion reference cell values not reflected in other sheet excel . 

### ISSUE THREAD

**Issue by Sathya272694** [jodconverter/jodconverter#349]
I have excel sheet it macros based excel I want to convert excel to pdf. One sheet cell values referred in other sheet  but it not reflected pdf . If any thing required to add like load properties 

>

**Comment by sbraconnier** [comment]
Are you able to properly convert the document, without jodonverter (using libreoffice only) ?

**Comment by sbraconnier** [comment]
Feel free to re-open if needed...
