### ISSUE TITLE
In jodconverter and its API does pagination (converting a certain page of docx/ppt/excel) to PNG uses MSOffice API internally?

### ISSUE THREAD

**Issue by Madhupatel08** [jodconverter/jodconverter#352]
How is the feature of pagination (converting a certain page of docx/ppt/excel) to PNG implemented using Libre or OpenOffice API? I did not find the calls for any of their endpoints for pagination (converting a certain page of docx/ppt/excel) to PNG. Great if folks could share where exactly in the code the call is being made.

ref: https://github.com/search?q=repo%3Ajodconverter%2Fjodconverter%20libre&type=code

cc @sbraconnier @EugenMayer @jgoldhammer @linux-warrior @nikowitt @mirkonasato 

Thank you so much!

**Comment by EugenMayer** [comment]
cc'ing 6 people in an opening of an OSS-repo issue is what gets you on my ignore list. Sorry.

**Comment by sbraconnier** [comment]
Well I agree with the previous comment. Be cautious about cc'ing people.

The work is done by a [filter](https://github.com/jodconverter/jodconverter/wiki/Using-Filters).

Take a look [here](https://github.com/jodconverter/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/local/filter/PagesSelectorFilter.java)

**Comment by Madhupatel08** [comment]
can you please tell me how to run JodConvertor? I'm getting the following error:

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/home/itcloud/.m2/repository/ch/qos/logback/logback-classic/1.2.11/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
Exception in thread "main" java.lang.IllegalStateException: This office manager is not running.
	at org.jodconverter.core.office.AbstractOfficeManagerPool.execute(AbstractOfficeManagerPool.java:206)
	at org.jodconverter.local.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:181)
	at org.jodconverter.core.job.AbstractConversionJob.execute(AbstractConversionJob.java:63)
	at org.example.PageFilterMultiPage.main(PageFilterMultiPage.java:33)
Disconnected from the target VM, address: '127.0.0.1:41585', transport: 'socket'
```
cc: @EugenMayer @sbraconnier

**Comment by sbraconnier** [comment]
I'm not sure I understand the question... There isn't a "one single call". The concept of JODConverter is doing programmatically what could be done manually. So, the manual steps for what you are trying to do are:

- You open the source document (docx,ppt, xls, whatever). This is done [here](https://github.com/jodconverter/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/local/task/AbstractLocalOfficeTask.java#L223)
- You "edit" the source document by deleting everything you don't want to be exported as PNG (this is what the [PageSelectorFilter](https://github.com/jodconverter/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/local/filter/PagesSelectorFilter.java) do.
- You export your edited document as PNG. This is done [here](https://github.com/jodconverter/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/local/task/LocalConversionTask.java#L202)

**Comment by Madhupatel08** [comment]
Currently, Jodconverter is writing the buffer `stream` (Java `Stream`) to PNG. It uses the filter `writer_png_Export` for text files. It breaks the input into a buffer stream, takes bytes from them, converts them into the desired output, and writes into the buffer stream. 

This buffer stream having extraction of text from say 2 pages, is then passed to LibreOffice API[*] to write that extracted text to PNG format.

Attached[1] is a screen recording of debugging points.

> You export your edited document as PNG. This is done [here](https://github.com/jodconverter/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/local/task/LocalConversionTask.java#L202)

In the method `storeDocument` conversion of `bufferstream` text/byte to a PNG is done. 
https://github.com/jodconverter/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/local/task/LocalConversionTask.java#L183-L216


While debugging, I'm unable to find the call made to convert the extracted text and store that into `TargetFile` which is a `PNG`. 

@sbraconnier: Can you link me to the final or any call or "the call" made to "The LibreOffice API" to convert/store/write this text of the multipage text file to PNG? This would ensure that the understanding of the flow of the Jodconverter and its architecture is correct.

The issue is I'm unable to find "The LibreOffice API endpoint" call which is by converting the extracted text of a multipage text file to PNG. Converting here means, writing/storing.

I would be happy to write a PR for the architecture or describe this feature in Jodconverter so that folks don't have to debug these many internal calls to find out the LibreOffice API call. 

[1] https://youtu.be/uLJd83JS35g
[*] https://listarchives.libreoffice.org/global/users/2023/msg00679.html 
[**] https://bugs.documentfoundation.org/show_bug.cgi?id=157425

**Comment by sbraconnier** [comment]
There isn't a single API endpoint call that does all the work.

I suggest you read [this](https://flywire.github.io/lo-p/) excellent website (chapter 1 in particular) that explain the technology used by jodconverter. It is not an easy API to use (not well documented and rather very complex IMO).

You may also find what you are looking for somewhere in the official OO wiki for developers:
https://wiki.openoffice.org/wiki/Documentation/DevGuide/OpenOffice.org_Developers_Guide
