### ISSUE TITLE
When converting DOCX to PDF the style is confused and many pages are lost

### ISSUE THREAD

**Issue by user599** [jodconverter/jodconverter#357]
jodconverter-version:4.4.6
LibreOffice-version:7.5.6.2
original document： **6 pages in total** （I emptied the text because they didn't affect the result)
![image](https://github.com/jodconverter/jodconverter/assets/41457884/e6969a07-5e0a-4df6-8326-40ba5c2f0abd)
PDF document: **only 3 pages and style was wrong**
![image](https://github.com/jodconverter/jodconverter/assets/41457884/13c6b127-0359-4f48-b195-d2c40d630d49)

**Comment by sbraconnier** [comment]
Is the behavior the same if you try to convert the document using LO manually (without jodconverter) ?

**Comment by user599** [comment]
Oh, yes, the same behavior occurs when I use `soffice  --convert-to pdf` command directly

**Comment by aksjondla** [comment]
Who knows the solution to this problem?
