### ISSUE TITLE
how to use it in android application ?

### ISSUE THREAD

**Issue by DevTrinh** [jodconverter/jodconverter#358]
I am trying to add this library to my android application however without success, how to configure it

**Comment by sbraconnier** [comment]
I will need a little more contact to help you. But know that this library requires a LibreOffice/OpenOffice installation somewhere that will execute the actual conversion. If you are using jodconverter remotely, you must have a server that can process conversion request.

Take a look [here](https://github.com/jodconverter/jodconverter-samples/tree/main/samples/spring-boot-rest) for an example.
