### ISSUE TITLE
Why Task was cancelled automatically

### ISSUE THREAD

**Issue by riverrsea** [jodconverter/jodconverter#360]
the exception like this:
> org.jodconverter.core.office.OfficeException: Task was cancelled: LocalConversionTask{source=SourceDocumentSpecsFromInputStream{file=null, format=null}, loadProperties={ReadOnly=true, Hidden=true, UpdateDocMode=0}, target=TargetDocumentSpecsFromOutputStream{file=null, format=pdf}, storeProperties=null, useStreamAdapters=false}

and below is my project Screenshot:

![image](https://github.com/jodconverter/jodconverter/assets/119987952/f2d1ac9a-a771-4212-9d7d-fb2fe843d078)
 + i use ssm frame to accept a doc from front-end and try to convert it into pdf, like the pic says, but it is failed. the document is not null by the way.

below is my configuration class:
![image](https://github.com/jodconverter/jodconverter/assets/119987952/570e94f6-27fd-4bb0-a6ce-0147586e1fa5)

as u see, i try to make the timeout  and process the most enough  and it still doesnt work.

**Comment by Funkynoob** [comment]
u may need this:
![image](https://github.com/jodconverter/jodconverter/assets/119987952/ce02a3c6-8c2a-4b74-a491-c2528f296ed9)

but i deploy it on windows which os i write the code and it worked! that's fxxk wired
