### ISSUE TITLE
High memory consumptiom while converting even 2-3MB of excel files to PDF

### ISSUE THREAD

**Issue by thetroubleshootingguy** [jodconverter/jodconverter#363]
Hey Team,

We are using this library extensively on our service to convert the excel to pdf and noticed that even the conversion of excel file with good volume of text and overall size of 2-3MB consuming the the heap size of 7-8 gigs. Has this behavior been reported? Is this a known behavior? Environments where this lib is used are very restricted and it is hard to extract heap dump from there, else I would have given it a look, but wondering if this has been already be reported before I take that route?

--tsguy

**Comment by thetroubleshootingguy** [comment]
Just a quick note, we convert the xlxs file first to HTML and then to PDF.

**Comment by sbraconnier** [comment]
Could you please share your jodconverter configuration ?

I would also need more info (jodconverter version, os, jvm, etc...) in order to try to anwser properly to that question.

**Comment by thetroubleshootingguy** [comment]
Here are details:

Java version:
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+9-Ubuntu-123.04)
OpenJDK 64-Bit Server VM (build 17.0.9+9-Ubuntu-123.04, mixed mode, sharing)

OS version:
PRETTY_NAME="Ubuntu 23.04"
NAME="Ubuntu"
VERSION_ID="23.04"
VERSION="23.04 (Lunar Lobster)"
VERSION_CODENAME=lunar
ID=ubuntu
ID_LIKE=debian

Jod converter properties:
jodconverter.local.enabled = True
jodconverter.local.port-numbers = 5500
jodconverter.local.processTimeout=300000
jodconverter.local.taskExecutionTimeout=300000
jodconverter.local.maxTasksPerProcess=50
jodconverter.local.taskQueueTimeout=120000

It is running within a k8s pod which has max of 4g and there is no min/max heap specified for the JVM to spawn with. So, it is default. Let me know if you need any further details on this.
________________________________

**Comment by thetroubleshootingguy** [comment]
Sorry I missed on updating what we are doing. We convert the incoming xlsx files to HTML first and then to PDF. Ultimate goal is to have PDF generated out of the incoming xlsx for further processing downstream.

Do you have any updates for me?

**Comment by sbraconnier** [comment]
Well, with that info I cannot pinpoint what could be the culprit.

Are you using LibreOffice ? And is it the LO/OO process that consumes the memory or if it is your application?

Without a look at the code, I cannot really help you. I suspect a memory leak somewhere. I didn't observe that kind of memory consumption running the [Stress Test](https://github.com/jodconverter/jodconverter/blob/master/jodconverter-local/src/integTest/java/org/jodconverter/local/StressITest.java) on my Windows using LibreOffice.

Did you check the logs file to see if there is an error that could explain this?

**Comment by sbraconnier** [comment]
Closing this one due to inactivity
