### ISSUE TITLE
Xslx SparkLine

### ISSUE THREAD

**Issue by phoekoby** [jodconverter/jodconverter#370]
Is available to export SparkLines to PDF from .xlsx /.xls files?
[sparkline.xlsx](https://github.com/jodconverter/jodconverter/files/14239814/sparkline.xlsx)

**Comment by sbraconnier** [comment]
Everything you can do without JodConverter (using LibreOffice only) should be doable with JodConverter.

So, the question is, are you able to export your file using LibreOffice only ?

**Comment by sbraconnier** [comment]
Feel free to re-open if needed...
