### ISSUE TITLE
Decimal number, from comma to dot 

### ISSUE THREAD

**Issue by kemuning** [jodconverter/jodconverter#371]
I have a .xlsx file with a number cell. With LO, the format in that cell is displayed with a comma ( decimal with comma - lang FR ), and when I exported as PDF, it is still displayed with a comma. But when I convert it with JOD, it is displayed with a dot ( decimal with dot - lang EN ). The conversion code I am using is just a common one :

```
public ByteArrayOutputStream doConvert(final DocumentFormat targetFormat, final InputStream inputFile) throws OfficeException {

    ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

    final DocumentConverter converter;

    converter = LocalConverter
                    .builder()
                    .officeManager(officeManager)
                    .build();

    converter
        .convert(inputFile)
        .to(outputStream)
        .as(targetFormat)
        .execute();

    return outputStream;
}
```

Any idea about this decimal format issue ?

**Comment by kemuning** [comment]
Thanks @sbraconnier for your reply. I am not sure if I understand the FilterOptions on that wiki page. Besides, the filter options are for CSV input file. There is also that Token 6 ... confusing.

**Comment by sbraconnier** [comment]
Can you please attach a sample file (xlsx) here I could work with with some cells you want to properly convert using comma instead of dots? I'll try to find the right options for you. It often takes some tries/errors before finding the right options/values we need.

**Comment by sbraconnier** [comment]
Hmmm. I just tested and on my end the output is the same as your test_LO.pdf. Obviously, there's something different with our setups. My OS language is EN (even if my primary language is FR). Maybe your's different? 

I'll try to find how to control this...

**Comment by kemuning** [comment]
Thanks @sbraconnier.

My OS language is EN ( Windows 11 ). But under the 'Country & region' setting, it is in FR.

Anyway, I tried to implement the templateProfileDir, but something not right because I am calling LocalConverter and not LocalOfficeManager :

```
@Slf4j
@Service
public class JODService extends BaseService {

    private final OfficeManager officeManager;

    public JODService(OfficeManager officeManager) {
        this.officeManager = officeManager;
    }

    public ByteArrayOutputStream doConvert(final DocumentFormat targetFormat, final InputStream inputFile) throws OfficeException {
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

        final DocumentConverter converter;
        converter = LocalConverter.builder()
                // .templateProfileDir("C:\\JodConverter\\LO\\templateProfile")
                .officeManager(officeManager)
		.build();

        log.info("==> JODConverter en action ...");
        converter
            .convert(inputFile)
            .to(outputStream)
            .as(targetFormat)
            .execute();

        return outputStream;
    }
}
```

What am I missing ?

**Comment by sbraconnier** [comment]
This property is for when you create the office manager. Are you using the spring boot module?

**Comment by kemuning** [comment]
Yes

**Comment by kemuning** [comment]
@sbraconnier I tried but I got this error : 
```
Caused by: java.lang.IllegalStateException: templateProfileDir doesn't appear to contain a user profile: C:\Users\ba111\Temp\LO\templateProfile
        at org.jodconverter.local.office.LocalOfficeUtils.validateOfficeTemplateProfileDirectory(LocalOfficeUtils.java:391)
        at org.jodconverter.local.office.LocalOfficeManager$Builder.build(LocalOfficeManager.java:206)
        at org.jodconverter.boot.autoconfigure.JodConverterLocalAutoConfiguration.createOfficeManager(JodConverterLocalAutoConfiguration.java:103)
        at org.jodconverter.boot.autoconfigure.JodConverterLocalAutoConfiguration.localOfficeManager(JodConverterLocalAutoConfiguration.java:151)
```

So I need to have a user profile in that templateProfileDir, but what user profile ? I checked again the wiki about it, but still don't understand. The LO user profile is located under %APPDATA%\libreoffice\4\user ( Windows 11 ).

And on the Tools->Options, I have this screenshot : 

![image](https://github.com/jodconverter/jodconverter/assets/23009699/d2b24a3a-b61f-4360-b65e-d43e1e85e633)

I am confused ...

**Comment by kemuning** [comment]
As per [here](https://github.com/jodconverter/jodconverter/issues/41#issuecomment-359625798), I did copied the whole C:\Users\ba111\AppData\Roaming\LibreOffice\4\user into my templateProfileDir , but the error remains.

**Comment by sbraconnier** [comment]
Try to follow the steps explained [here](https://github.com/jodconverter/jodconverter/issues/41#issuecomment-359625798)

I'm currently using this property a lot cuz LO won't even start as a service on my laptop if OpenGL is enabled to begin with.

You must  copy your `%APPDATA%\libreoffice\4\user` (including the user directory) under the directory you will set as `templateProfileDir`

On my laptop, the property is set to `C:/workarea/LO/config/templateProfileDir`, and the content of this directory is:

```
templateProfileDir
------/user
------------/autocorr
------------/autotext
------------/etc...
```

So I only have a single `user` directory under the templateProfileDir directory. Not super intuitive but we must keep it that way for backward compatibility and because it's the hierarchy LO is expecting.

**Comment by sbraconnier** [comment]
> As per https://github.com/jodconverter/jodconverter/issues/41#issuecomment-359625798, I did copied the whole C:\Users\ba111\AppData\Roaming\LibreOffice\4\user into my templateProfileDir , but the error remains.

If you take a second look, it's `C:\Users\ba111\AppData\Roaming\LibreOffice\4` you should have read, not `C:\Users\ba111\AppData\Roaming\LibreOffice\4\user`

**Comment by kemuning** [comment]
Yes, I found your answer [here](https://github.com/jodconverter/jodconverter/issues/76#issuecomment-387831507)

The error is gone.

**Comment by kemuning** [comment]
And the decimal format is also gone.
Thanks @sbraconnier

**Comment by sbraconnier** [comment]
Very glad to hear that :)
