### ISSUE TITLE
Information about supported properties and their meaning

### ISSUE THREAD

**Issue by The-Real-1** [jodconverter/jodconverter#372]
Hi,

We are currently trying to handle conversions from **.doc** and **.docx** files to **.odt** and **.ott**.  Our scenarios, for most of them, consist in managing templates transformations. We know there are some limitations  between the formats and we are trying to understand some of the internals behaviours of JodConverter to find out a solution. 

We have a question about the **DEFAULT_LOAD_PROPERTIES** parameter (visible in LocalConverter for example)

```java
  static {
    final Map<String, Object> loadProperties = new HashMap<>();
    loadProperties.put("Hidden", true);
    loadProperties.put("ReadOnly", true);
    loadProperties.put("UpdateDocMode", UpdateDocMode.NO_UPDATE);

    DEFAULT_LOAD_PROPERTIES = Collections.unmodifiableMap(loadProperties);
  }
```

There are 3 default properties set here, but they are not specified anywhere else.
We are really interested in having a full list of supported properties and their meaning. 

Do you know where we could find it ?  

Thanks for the help.

Regards

**Comment by The-Real-1** [comment]
We found it ! 
For those interested : 

**https://www.openoffice.org/api/docs/common/ref/com/sun/star/document/MediaDescriptor.html**

**Comment by sbraconnier** [comment]
Maybe a more up to date reference (LibreOffice):
https://api.libreoffice.org/docs/idl/ref/servicecom_1_1sun_1_1star_1_1document_1_1MediaDescriptor.html

When I want to see which "export to PDF FilterData" properties are supported, why not looking directly at the source code!:
https://github.com/LibreOffice/core/blob/master/filter/source/pdf/pdfexport.cxx#L518

And a website I really enjoy to undestand the basics about LibreOffice programming using the UNO Api:
https://flywire.github.io/lo-p/
