### ISSUE TITLE
Same issue with Temporary file name added in CSV -> PDF conversion

### ISSUE THREAD

**Issue by lilylei013** [jodconverter/jodconverter#374]
Hi @sbraconnier, I am facing same issue like [https://github.com/jodconverter/jodconverter/issues/219](url)  while converting any CSV file to PDF using jodconverter. you can just new a csv file add any context, when use jodconvert to pdf, the pdf will contain tempfile_XXX in the header, and page in the footer, while convert xlsx to pdf have no same issue, I tried open the csv file in libreoffice, and export to pdf, also have  tempfile_XXX in the header, and page in the footer, seems this is libreoffice config setting, but I don't know how to config it, can you help with this. not sure if the libreoffice setting is related to this 
![image](https://github.com/jodconverter/jodconverter/assets/36144717/9a0446ea-1fb4-4209-bae9-2bf2d80f9acf)
https://wiki.documentfoundation.org/Documentation/DevGuide/Spreadsheet_Documents

**Comment by sbraconnier** [comment]
This seems to have been fixed in recent LibreOffice version. Which version are you using ??

**Comment by sbraconnier** [comment]
Well, after some digging, you seem to be hitting [this issue](https://bugs.documentfoundation.org/show_bug.cgi?id=144056), which is not resolved. 

So according to the suggestions, your best bet would be to remove programatically the header/footer.

Here's how you could do it, with [this](https://stackoverflow.com/a/37507298) post as an inspiration. Please modify the function as you see fit.

```java
private static void convertCsvToPdfRemovingHeaderFotter(final OfficeManager manager) throws OfficeException {

    final File inputFile = new File("C:\\tmp\\jodc\\test.csv");
    final File outputFile = new File("C:\\tmp\\jodc\\test.pdf");

    LocalConverter
            .builder()
            .officeManager(manager)
            .filterChain((context, document, chain) -> {

                if (Calc.isCalc(document)) {

                    // Remove header/footer from default page style.

                    // Access the 'PageStyles' Family
                    final XStyleFamiliesSupplier xSupplier =  Lo.qi(XStyleFamiliesSupplier.class, document);
                    final XNameContainer xFamily = Lo.qi(XNameContainer.class, xSupplier.getStyleFamilies().getByName("PageStyles"));

                    // Now acess the Default PageStyle
                    final XStyle xStyle = Lo.qi(XStyle.class, xFamily.getByName("Default"));

                    // Turn off header and footer
                    final XPropertySet xStyleProps = Lo.qi(XPropertySet.class, xStyle);
                    xStyleProps.setPropertyValue("HeaderIsOn", false);
                    xStyleProps.setPropertyValue("FooterIsOn", false);
                }

                // Invoke the next filter in the chain.
                chain.doFilter(context, document);
            })
            .build()
            .convert(inputFile)
            .to(outputFile)
            .execute();
}
```

**Comment by lilylei013** [comment]
Thank you for the answer, this works for me
