### ISSUE TITLE
jodconverter-local 4.4.3 or later causes the service to fail to end.

### ISSUE THREAD

**Issue by tongchenghao** [jodconverter/jodconverter#375]
jodconverter-local 4.4.2 is fine. However, after the upgrade, the service cannot be ended.

**Comment by tongchenghao** [comment]
![image](https://github.com/jodconverter/jodconverter/assets/54256981/8b88159c-b5fa-420b-91e9-76c0a1530590)

**Comment by tongchenghao** [comment]
![image](https://github.com/jodconverter/jodconverter/assets/54256981/c0eec6c8-88bf-4584-b99f-d90d909a44e6)

**Comment by tongchenghao** [comment]
![image](https://github.com/jodconverter/jodconverter/assets/54256981/d48cb726-eb57-471d-aba4-c954a862e34a)

**Comment by sbraconnier** [comment]
I'm not sure I quite understand... Can you post both logs (4.4.2 and 4.4.3+) so we can see the difference and what you are expecting ?? 

Since your last log line starts with the term "success", I'm not sure what is the problem exactly...

**Comment by tongchenghao** [comment]
log is same，but 4.4.2 can exit java Processes sucess，4.4.3 can not

**Comment by sbraconnier** [comment]
I was unable to reproduce the issue locally. This will be a tricky one to resolve. 

Would it be possible for you to provide a full log (you can remove sensitive lines not related to jodconverter) with the log level set to DEBUG for both 4.4.2 and 4.4.3 (or even better, the latest version 4.4.7). I need info not just when the process is supposed to end, but also when it is started, thus the full application log would be great. You can email it to me if you prefer.

Thanks.

**Comment by tongchenghao** [comment]
Check whether the 4.4.2 version of jodconverter-local does not verify whether the associated officeHome process exits when the service exits, while the 4.4.3+ version will wait for the associated officeHome process to exit before ending the service.

**Comment by tongchenghao** [comment]
When I end the service, I don't call OfficeManager.stop, so the associated process doesn't end, blocking the end of the service. But 4.4.2 doesn't care about that.

**Comment by sbraconnier** [comment]
Sorry for the long delay. I didn't had time to work on this until now. I think I found the source of your problem, but I'm not sure. So I've uploaded a 4.4.8-SNAPSHOT version, which is available in the [oss snapshot maven repository](https://oss.sonatype.org/content/repositories/snapshots/).

Would it be possible for you to test it??
