### ISSUE TITLE
org.jodconverter.core.office.OfficeException: Task was cancelled: LocalConversionTask

### ISSUE THREAD

**Issue by DeminIgor** [jodconverter/jodconverter#376]
Good afternoon

Configured JodConverter together with Libreoffice.

The file is converted normally if this method is currently accessed by one user and only once.

If you access a method from two different sessions at the same time, or twice at the same time from the same session, you see an error.

Tell me, is it possible to configure LocalOfficeManager so that it processes many requests at the same time?

4.4.7 version

<img width="895" alt="Снимок экрана 2024-03-14 в 21 21 57" src="https://github.com/jodconverter/jodconverter/assets/66465979/87aedeff-5fb0-406a-b22c-7ca776a0efea">

**Comment by sbraconnier** [comment]
I'm am currently boarding in an airplane, so I won't be able to elaborate so much, but you seem to start 1 office manager managing 4 office processes for each conversion request. You then close the manager, which terminates the 4 office processes. This is not the way to use jodconverter for a web application. You should start the manager once on application start and close on application end. 

You have some examples here in how to use it for web application

https://github.com/jodconverter/jodconverter-samples

**Comment by DeminIgor** [comment]
Good afternoon
Thank you!
It really works!

I have one more question.
Is it possible to set up conversion if the service that converts files and the service in which libreoffice is installed are in different docker containers?

**Comment by sbraconnier** [comment]
Yes,

You should be able to do this by using the `ExternalOfficeManager`

```java
final ExternalOfficeManager officeManager = ExternalOfficeManager
        .builder()
        .hostName("127.0.0.1") // This is the default, but you can set the IP address you want.
        .portNumbers(2002, 2003, 2004, 2005)
        .maxTasksPerConnection(0)
        .install()
        .build();
```

**Comment by DeminIgor** [comment]
> I am personnally not familiar with docker, but I know from past questions that some jodconverter users have sucessfully done what you are trying to do. They didn't shared their project tho so I can't linked a specific question with the full recipe. If you succeed, please share what you did to make this work!! You can search for the term "Docker" without any other filter in the jodconverter issues.

I got something. Indeed, ExternalOfficeManager from a container with a java service does not launch the libreoffice process in a container with libreoffice. I run it manually with the command you specified earlier.
In this case, the conversion is processed once and then there are connection errors. Now I need to configure libreoffice processes so that they are stable.

**Comment by sbraconnier** [comment]
Feel free to re-open if needed.
