### ISSUE TITLE
Please remove unnecessary `@ConfigurationPropertiesScan` on `JodConverterLocalProperties` and `JodConverterRemoteProperties`

### ISSUE THREAD

**Issue by bianjp** [jodconverter/jodconverter#377]
`JodConverterLocalProperties` and `JodConverterRemoteProperties` are conditionally activated by corresponding AutoConfiguration class through `@EnableConfigurationProperties`, so annotating them with `@ConfigurationPropertiesScan` is unnecessary.

What's worse is that `@ConfigurationPropertiesScan` caused unexpected side effect:

1. When `JodConverterLocalAutoConfiguration` matches, `JodConverterRemoteProperties` will be scanned by `@ConfigurationPropertiesScan`, even though `JodConverterRemoteAutoConfiguration` does not match.
2. Similarly, `JodConverterLocalProperties` will also be scanned even though `JodConverterLocalAutoConfiguration` does not match.

Normally registering a useless ConfigurationProperties bean causes no harm, but in some cases it really does:

1. Someone has reported in #345: When `jodconverter.remote.ssl.enabled=false` is provided in `application.properties` but `jodconverter-remote` is not present in the classpath, Spring failed to start with `ClassNotFoundException: org.jodconverter.remote.ssl.SslConfig`
2. When using [jasypt-spring-boot 2.1.x](https://github.com/ulisesbocchio/jasypt-spring-boot), Spring also failed to start with `ClassNotFoundException: org.jodconverter.remote.ssl.SslConfig`, even though no `jodconverter.remote.ssl.*` properties were found.
    * This happens because jasypt wraps every PropertySource with a custom wrapper and unexpectedly changes the behavior of [Binder#containsNoDescendantOf](https://github.com/spring-projects/spring-boot/blob/v2.7.18/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/bind/Binder.java#L394). It makes `containsNoDescendantOf` to return `false`, so Spring blindly tries to bind `JodConverterRemoteProperties#ssl` even no properties are found.
    * This was fixed in 3.0.4 by [skip wrapping `StubPropertySource`](https://github.com/ulisesbocchio/jasypt-spring-boot/issues/264)
    * Though it is jasypt to blame, this can be avoided if JodConverter does not register `JodConverterRemoteProperties` bean

I suggest removing the `@ConfigurationPropertiesScan` annotation on `JodConverterLocalProperties` and `JodConverterRemoteProperties`.

**Comment by EugenMayer** [comment]
@sbraconnier pretty sure i did not add that intentional or actually myself - not using this annotation usually - or at least i cannot remember.

The PR sounds good to me, also thank you @bianjp for elaborating in such detail. LGTM there

**Comment by sbraconnier** [comment]
@EugenMayer It seems to have appeared here => a901ce120435bf4e2dfb216680aa39354e750d39 <= but I may be reading the history wrong. Thanks for your feedback!

@bianjp Thanks for the catch!
