### ISSUE TITLE
WindowsProcessManager#isUsable triggers antivirus

### ISSUE THREAD

**Issue by pg-wtatum** [jodconverter/jodconverter#388]
The `wmic quit` call in WindowsProcessManager#isUsable is currently triggering my corporate antivirus and killing the entire Java process. I tried to work around by manually configuring Spring to use PureJavaProcessManager::getDefault but this did not resolve the issue since LocalOfficeManager.Builder sets this default value inside this builder

private ProcessManager processManager = LocalOfficeUtils.findBestProcessManager();

This means even if the builder is later configured differently the initial code for findBestProcessManager runs and AV kills the process.

I'm working with IT for an exception for dev environment but wanted to see if there was a clearer workaround? I suppose it would consist of directly constructing LocalOfficeManager without the builder? Any more ergonomic option or any possible changes to the process manager to make it less repugnant to AV software?

**Comment by sbraconnier** [comment]
I'm afraid there is no easy way for you at this time. The constructor of the `LocalOfficeManager` is private (you must use the builder).

Could you please test the `4.4.8-SNAPSHOT` version? I made a small change so the `processManager` of the builder will be initialized using the `findBestProcessManager` only if not already set. You could then use the `PureJavaProcessManager`, or a custom one you would have created for you needs. I'm not a fan of the `PureJavaProcessManager` cuz it doesn't support finding the PID.

You will need to add the oss sonatype snapshots repo for your dependencies:
https://oss.sonatype.org/content/repositories/snapshots

**Comment by sbraconnier** [comment]
Fix in 4.4.8
