### ISSUE TITLE
Any particular reason we do not support xlsm in DefaultDocumentFormatRegistry

### ISSUE THREAD

**Issue by EugenMayer** [jodconverter/jodconverter#391]
Currently, converting xlsm files is not possible since we do not have a registry entry. Is this by design and does it simply not work or is this something that might have been forgotten and we should add those?

**Comment by sbraconnier** [comment]
No there isn't a reason :) I'll add it. I'm not sure that it'is not already possible to convert from xlsm to another format tho. The registry is used to find the proper FilterName when converting TO a specific format.

**Comment by EugenMayer** [comment]
Thank you @sbraconnier - didnt want to offload the burden to you for the PR, just always asking about intentions before brutally stuffing in a PR without context :)

Any way, thank you a lot!
