### ISSUE TITLE
When start app using jodconverter-spring-boot-starter, soffice.bin is considered a zombie process

### ISSUE THREAD

**Issue by mylutte** [jodconverter/jodconverter#392]
When start app using jodconverter-spring-boot-starter, soffice.bin is considered a zombie process

jodconverter version：4.4.2
LibreOffice version：7.2.7

**Comment by sbraconnier** [comment]
I think I found the source of your problem, but I'm not sure. So I've uploaded a 4.4.8-SNAPSHOT version, which is available in the [oss snapshot maven repository](https://oss.sonatype.org/content/repositories/snapshots/).

Would it be possible for you to test it??

**Comment by mylutte** [comment]
THX, i'll try it later, but I've upgraded LibreOffice to the latest stable version now, and there don't seem to be any zombie process.

BTW, does our jodconverter have this feature , such as by configuring, reach a certain period of time, office is inactive, automatically shut down, to prevent long-term unuse, in a zombie state.

**Comment by sbraconnier** [comment]
No it doesn't. Launching an office process and connecting to it is not like creating a database connection, it may take a long time, several seconds. So it is best to do this once  when the applications starts so the launching of office process is not something you have to wait for (if the [`startFailFast`](https://github.com/jodconverter/jodconverter/wiki/Configuration#white_check_markstartfailfast) switch is off).
