### ISSUE TITLE
Question: PDF File Vertical Margins Problem 

### ISSUE THREAD

**Issue by w-c267** [jodconverter/jodconverter#406]
I have to convert xlsx to pdf on Linux using Libre Office.
I can convert xlsx to pdf as print preview on Windows.
Compared to Windows, a converted pdf file has much wider vertical margins on Linux.
I 've tried the Filter class config to reduce margins. But it didn't work well.
Could you tell me how to narrow vertical margins on Linux?

### Specifications
jodconverter: 4.4.7
Libre Office: 7.6
#### OS
Windows 11
CentOS
#### font
NotoSansJP

**Comment by medi6** [comment]
Hi, 
I've got the same problem with Libre Office 7.6 (Alpine version). 
Using Libre Office 7.5 fixed it, and I don't know why.

**Comment by w-c267** [comment]
Thank you for your reply.
Though I tried Libre Office 7.5, nothing has changed.
I'm looking for the way to manipluate colum width(height) via XSpreadsheet.
Narrowing colum width, a converted document fits to moderate marigins.
I've found it using jodconverter cli tool.
